tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "cloudfoundry/tap"
tap "romkatv/powerlevel10k"
tap "Rigellute/tap"
tap "k14s/tap"

# Microsoft Azure CLI 2.0
brew "azure-cli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat" 
# Encoding tool
brew "ffmpeg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Distributed revision control system
brew "git"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Platform built on V8 to build network applications
brew "node"
# Programatically correct mistyped console commands
brew "thefuck"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Powerline10k
brew "romkatv/powerlevel10k/powerlevel10k"
# Terminal Multiplexer
brew "tmux"
# Show System information
brew "neofetch"
# Youtube stuff
brew "youtube-dl"
# Like top but written in go 
brew "gotop"
# Update bash  
brew "bash"
# bash ShellCheck 
brew "shellcheck"
# static site generator
brew "hugo"

## Kubernetes STUFF
brew "kubectl"
# Kubernetes in docker
brew "kind"
# Simple deployment tool
brew "kapp"
# Yml templating helper
brew "ytt"

## Docker STUFF
# docker tool to look into the images / layers
brew "dive"

## Cloud Foundry STUFF
#Cloud Foundry CLI
brew "cloudfoundry/tap/cf-cli"
brew "cloudfoundry/tap/bosh-cli"

## RUBY STUFF
# ruby version manager
brew "rbenv"
#change current ruby
brew "chruby"